package net.globulus.simi;

enum TokenType {
  // Single-character tokens.
  LEFT_PAREN, RIGHT_PAREN, LEFT_BRACKET, RIGHT_BRACKET,
  COMMA, DOT, COLON, NEWLINE,

  // One or two character tokens.
  BANG, BANG_EQUAL,
  EQUAL, EQUAL_EQUAL,
  GREATER, GREATER_EQUAL,
  LESS, LESS_EQUAL,
  LESS_GREATER,
    PLUS, PLUS_EQUAL,
    MINUS, MINUS_EQUAL,
  STAR, STAR_STAR, STAR_EQUAL,
    SLASH, SLASH_EQUAL,
  MOD, MOD_MOD, MOD_EQUAL,
  DOLLAR_LEFT_BRACKET,
  QUESTION, QUESTION_QUESTION,

  // Literals.
  IDENTIFIER, STRING, NUMBER,

  // Keywords.
  AND, BREAK, CLASS, CONTINUE, ELSE, FALSE, DEF, FOR, RESCUE,
  IF, NIL, OR, PRINT, RETURN, SUPER, SELF, TRUE, WHILE, PASS,
  IN, IS, NOT, ELSIF, END, ISNOT, NOTIN, NATIVE, IMPORT,

  GU,

  EOF
}
